approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
author_approval: ignored
reset_on_push: true
reset_on_reopened: true
reviewers:
  members:
  - oterrien
  - oterrientest
  name: default
  required: 1
